-- ai generated
local function enum(max, values, allow_boolean)
	return {
		type = 'enum',
		values = values,
		min = 0,
		max = max,
		allow_boolean = allow_boolean,
	}
end

local boolean = { type = 'boolean' }
local integer = { type = 'integer' }
local integer_boolean = { type = 'integer', allow_boolean = true }
local unsigned = {
	type = 'integer',
	min = 0,
	max = 4294967295,
	values = { auto = 0 },
}
local string_value = { type = 'string' }

local base_values = {
	bin = 2,
	binary = 2,
	oct = 8,
	octal = 8,
	dec = 10,
	decimal = 10,
	duo = 12,
	duodecimal = 12,
	hex = 16,
	hexadecimal = 16,
	sexa = 60,
	sexagesimal = 60,
	sexagesimal2 = 62,
	sexagesimal_2 = 62,
	sexagesimal3 = 63,
	sexagesimal_3 = 63,
	latitude = 70,
	latitude2 = 71,
	latitude_2 = 71,
	longitude = 72,
	longitude2 = 73,
	longitude_2 = 73,
	time = -2,
	roman = -1,
	unicode = -4,
	golden = -5,
	golden_ratio = -5,
	['φ'] = -5,
	supergolden = -6,
	supergolden_ratio = -6,
	['ψ'] = -6,
	pi = -7,
	['π'] = -7,
	e = -8,
	sqrt2 = -9,
	['sqrt(2)'] = -9,
	bcd = -20,
	bijective = -26,
	b26 = -26,
	fp16 = -30,
	binary16 = -30,
	fp32 = -31,
	binary32 = -31,
	float = -31,
	fp64 = -32,
	binary64 = -32,
	double = -32,
	fp128 = -33,
	binary128 = -33,
	fp80 = -34,
}

local number_base = { type = 'integer', values = base_values }

local exponent_threshold = {
	type = 'integer',
	values = {
		off = 0,
		auto = -1,
		engineering = -3,
		pure = 1,
		scientific = 3,
	},
}

local enums = {
	read_precision = enum(2, {
		off = 0,
		always = 1,
		when_decimals = 2,
	}),
	angle_unit = enum(4, {
		none = 0,
		rad = 1,
		radians = 1,
		deg = 2,
		degrees = 2,
		gra = 3,
		gradians = 3,
		custom = 4,
	}),
	parsing_mode = enum(4, {
		adaptive = 0,
		implicit_first = 1,
		implicit_multiplication_first = 1,
		conventional = 2,
		chain = 3,
		rpn = 4,
	}),
	base_display = enum(3, {
		none = 0,
		normal = 1,
		alternative = 2,
		suffix = 3,
	}),
	number_fraction_format = enum(8, {
		decimal = 0,
		off = 0,
		decimal_exact = 1,
		exact = 1,
		fractional = 2,
		on = 2,
		combined = 3,
		mixed = 3,
		fractional_fixed_denominator = 4,
		combined_fixed_denominator = 5,
		percent = 6,
		permille = 7,
		permyriad = 8,
	}),
	use_unicode_signs = enum(3, {
		off = 0,
		on = 1,
		units = 2,
		only_unit_exponents = 2,
		without_exponents = 3,
	}, true),
	multiplication_sign = enum(3, {
		asterisk = 0,
		['*'] = 0,
		dot = 1,
		x = 2,
		['×'] = 2,
		altdot = 3,
	}),
	division_sign = enum(2, {
		slash = 0,
		['/'] = 0,
		division_slash = 1,
		['⁄'] = 1,
		division = 2,
		['÷'] = 2,
	}),
	interval_display = enum(7, {
		significant = 0,
		significant_digits = 0,
		interval = 1,
		plusminus = 2,
		midpoint = 3,
		lower = 4,
		upper = 5,
		concise = 6,
		relative = 7,
	}),
	digit_grouping = enum(2, {
		off = 0,
		none = 0,
		standard = 1,
		on = 1,
		locale = 2,
	}),
	date_time_format = enum(1, { iso = 0, locale = 1 }),
	time_zone = enum(2, { utc = 0, ['local'] = 1, local_time = 1, custom = 2 }),
	exp_display = enum(3, {
		default = 0,
		uppercase_e = 1,
		lowercase_e = 2,
		power_of_10 = 3,
	}),
	rounding = enum(10, {
		half_away_from_zero = 0,
		standard = 0,
		half_to_even = 1,
		even = 1,
		half_to_odd = 2,
		half_toward_zero = 3,
		half_up = 4,
		half_down = 5,
		half_random = 6,
		toward_zero = 7,
		truncate = 7,
		away_from_zero = 8,
		up = 9,
		down = 10,
	}),
	approximation = enum(2, {
		exact = 0,
		try_exact = 1,
		auto = 1,
		approximate = 2,
	}),
	auto_post_conversion = enum(3, {
		none = 0,
		best = 1,
		si = 1,
		optimal_si = 1,
		optimalsi = 1,
		base = 2,
		optimal = 3,
	}),
	mixed_units_conversion = enum(5, {
		none = 0,
		downwards_keep = 1,
		downwards = 2,
		default = 3,
		force_integer = 4,
		force_all = 5,
	}),
	structuring = enum(2, {
		none = 0,
		expand = 1,
		simplify = 1,
		factorize = 2,
	}),
	complex_number_form = enum(3, {
		rectangular = 0,
		exponential = 1,
		polar = 2,
		cis = 3,
	}),
	interval_calculation = enum(3, {
		none = 0,
		variance = 1,
		variance_formula = 1,
		iv = 2,
		interval_arithmetic = 2,
		simple_interval_arithmetic = 3,
	}),
}

local schemas = {
	parse_options = {
		variables_enabled = boolean,
		functions_enabled = boolean,
		units_enabled = boolean,

		dot_as_separator = boolean,
		comma_as_separator = boolean,
		brackets_as_parentheses = boolean,
		preserve_format = boolean,

		base = number_base,
		binary_bits = unsigned,
		twos_complement = boolean,
		hexadecimal_twos_complement = boolean,

		read_precision = enums.read_precision,
		parsing_mode = enums.parsing_mode,
		angle_unit = enums.angle_unit,
	},

	print_options = {
		preserve_format = boolean,
		allow_non_usable = boolean,
		allow_factorization = boolean,

		spacious = boolean,
		excessive_parenthesis = boolean,
		hide_underscore_spaces = boolean,
		spell_out_logical_operators = boolean,
		comma_sign = string_value,
		decimalpoint_sign = string_value,
		multiplication_sign = enums.multiplication_sign,
		division_sign = enums.division_sign,
		digit_grouping = enums.digit_grouping,
		use_unicode_signs = enums.use_unicode_signs,

		abbreviate_names = boolean,
		use_reference_names = boolean,
		place_units_separately = boolean,
		use_unit_prefixes = boolean,
		use_prefixes_for_all_units = boolean,
		use_prefixes_for_currencies = boolean,
		use_all_prefixes = boolean,
		use_denominator_prefix = boolean,

		negative_exponents = boolean,
		halfexp_to_sqrt = boolean,
		exp_to_root = boolean,
		min_exp = exponent_threshold,
		exp_display = enums.exp_display,

		base = number_base,
		binary_bits = unsigned,
		twos_complement = boolean,
		hexadecimal_twos_complement = boolean,
		duodecimal_symbols = boolean,
		lower_case_numbers = boolean,
		base_display = enums.base_display,

		indicate_infinite_series = boolean,
		show_ending_zeroes = boolean,
		preserve_precision = boolean,
		interval_display = enums.interval_display,

		min_decimals = integer,
		max_decimals = integer,
		use_min_decimals = boolean,
		use_max_decimals = boolean,
		restrict_to_parent_precision = boolean,
		rounding = enums.rounding,

		restrict_fraction_length = boolean,
		number_fraction_format = enums.number_fraction_format,

		short_multiplication = boolean,
		improve_division_multipliers = boolean,

		custom_time_zone = integer,
		time_zone = enums.time_zone,
		date_time_format = enums.date_time_format,

		sort_options = {
			type = 'table',
			fields = {
				prefix_currencies = boolean,
				minus_last = boolean,
			},
		},
	},

	evaluation_options = {
		calculate_variables = boolean,
		calculate_functions = boolean,
		test_comparisons = integer_boolean,
		isolate_x = boolean,
		assume_denominators_nonzero = integer_boolean,
		warn_about_denominators_assumed_nonzero = boolean,
		transform_trigonometric_functions = boolean,
		approximation = enums.approximation,
		interval_calculation = enums.interval_calculation,

		keep_prefixes = boolean,
		keep_zero_units = boolean,
		sync_units = boolean,
		sync_nonlinear_unit_relations = boolean,
		local_currency_conversion = boolean,
		auto_post_conversion = enums.auto_post_conversion,
		mixed_units_conversion = enums.mixed_units_conversion,

		expand = integer_boolean,
		split_squares = boolean,
		reduce_divisions = boolean,
		combine_divisions = boolean,
		do_polynomial_division = boolean,
		structuring = enums.structuring,

		allow_infinite = boolean,
		allow_complex = boolean,
		complex_number_form = enums.complex_number_form,
	},
}

return schemas
